version: "3"

services:
  app:
    build: .
    image: fastapi-app
    command: uvicorn app.main:app --host 0.0.0.0 --port $PORT --reload
    container_name: fastapi-app-service
    ports:
      - "9001:9001"
      - "${PORT}:${PORT}"
    healthcheck:
      test: curl -f http://localhost:${PORT}/
    restart: always
    env_file: .env
    volumes:
      - ./:$PROJECT_ROOT
