version: "3"

services:
  app:
    build: .
    image: fastapi-app
    command: uvicorn app.main:app --host 0.0.0.0 --port $PORT --reload
#    command: gunicorn -k uvicorn.workers.UvicornWorker app.main:app
    container_name: fastapi-app-service
    ports:
      - "9001:9001"
      - "${PORT}:${PORT}"
    healthcheck:
      test: curl -f http://localhost:${PORT}/
    restart: always
    env_file: .env
    volumes:
      - ./:$PROJECT_ROOT
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/nginx.conf:ro
      - ./ui/:/home/project/
    container_name: server
    restart: always
